spring:
  datasource:
    url: jdbc:h2:mem:todolist_test_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

app:
  name: To-Do List Manager
  version: 1.0.0
  environment: Test